name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *"  # Menjalankan setiap tengah malam UTC

  workflow_dispatch: # Memungkinkan menjalankan workflow secara manual

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create output directory
        run: mkdir -p output

      - name: Generate Snake Animation
        uses: Platane/snk@v2
        with:
          github_user_name: ${{ github.marcellohugo }}
          outputs: output/github-contribution-grid-snake.svg

      - name: Upload Snake Animation
        uses: actions/upload-artifact@v4
        with:
          name: snake-animation
          path: output/github-contribution-grid-snake.svg
