name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *"  # Menjalankan setiap tengah malam UTC
  workflow_dispatch: # Memungkinkan menjalankan workflow secara manual

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate Snake Animation
        uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: github-contribution-grid-snake.svg

      - name: Setup Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Commit and Push Snake Animation
        run: |
          git checkout -B output  # Pastikan berada di branch output
          git add github-contribution-grid-snake.svg
          git commit -m "Update GitHub Contribution Snake"
          git push origin output --force
